blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discord.com/channels/883083792112300104/987730774285516800
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/awcodes/filament-sticky-header/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/awcodes/filament-sticky-header/security/policy
    about: Learn how to notify us for sensitive bugs